import 'hourly_forecast.dart';
import 'weather_condition.dart';
import 'weather_model.dart';

/// Deterministic weather fixtures for testing and visual qualification.
/// Each fixture represents a distinct atmospheric state.
abstract class ConditionFixtures {
  static final WeatherModel clearDay = WeatherModel(
    location: 'Clear Valley',
    temperature: 72,
    condition: WeatherCondition.sunny,
    feelsLike: 71,
    high: 78,
    low: 62,
    humidity: 35,
    windSpeedMph: 4,
    uvIndex: 8,
    pressureInHg: 30.12,
    precipChance: 0,
    totalRainInches: 0,
    visibilityMiles: 10,
    windDirectionCompass: 'S',
    windBearingDegrees: 180,
    sunriseTime: '6:15 AM',
    sunsetTime: '7:45 PM',
    daylightDuration: '13h 30m',
    dailySummary: 'Clear skies and warm sunshine.',
    riskLevel: 'LOW RISK',
    severeRisks: const <String, double>{},
    whatToExpect: const <String>['Full sun', 'Pleasant'],
    impactScores: const <String, int>{'Weather': 0},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel clearNight = WeatherModel(
    location: 'Clear Valley',
    temperature: 52,
    condition: WeatherCondition.sunny,
    feelsLike: 50,
    high: 78,
    low: 52,
    humidity: 45,
    windSpeedMph: 3,
    uvIndex: 0,
    pressureInHg: 30.14,
    precipChance: 0,
    totalRainInches: 0,
    visibilityMiles: 10,
    windDirectionCompass: 'SW',
    windBearingDegrees: 225,
    sunriseTime: '6:15 AM',
    sunsetTime: '7:45 PM',
    daylightDuration: '13h 30m',
    dailySummary: 'Clear night with stars visible.',
    riskLevel: 'LOW RISK',
    severeRisks: const <String, double>{},
    whatToExpect: const <String>['Clear', 'Calm'],
    impactScores: const <String, int>{'Weather': 0},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel partlyCloudyDay = WeatherModel(
    location: 'Cloud Summit',
    temperature: 68,
    condition: WeatherCondition.cloudy,
    feelsLike: 67,
    high: 74,
    low: 58,
    humidity: 48,
    windSpeedMph: 7,
    uvIndex: 5,
    pressureInHg: 30.08,
    precipChance: 10,
    totalRainInches: 0,
    visibilityMiles: 10,
    windDirectionCompass: 'W',
    windBearingDegrees: 270,
    sunriseTime: '6:10 AM',
    sunsetTime: '7:50 PM',
    daylightDuration: '13h 40m',
    dailySummary: 'Partly cloudy with occasional breaks.',
    riskLevel: 'LOW RISK',
    severeRisks: const <String, double>{},
    whatToExpect: const <String>['Mixed sun', 'Comfortable'],
    impactScores: const <String, int>{'Weather': 0},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel overcast = WeatherModel(
    location: 'Gray Mountains',
    temperature: 62,
    condition: WeatherCondition.cloudy,
    feelsLike: 60,
    high: 68,
    low: 56,
    humidity: 62,
    windSpeedMph: 9,
    uvIndex: 2,
    pressureInHg: 30.02,
    precipChance: 20,
    totalRainInches: 0,
    visibilityMiles: 9,
    windDirectionCompass: 'NW',
    windBearingDegrees: 315,
    sunriseTime: '6:05 AM',
    sunsetTime: '7:55 PM',
    daylightDuration: '13h 50m',
    dailySummary: 'Overcast skies with full cloud cover.',
    riskLevel: 'LOW RISK',
    severeRisks: const <String, double>{},
    whatToExpect: const <String>['Overcast', 'Cool'],
    impactScores: const <String, int>{'Weather': 0},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel lightRain = WeatherModel(
    location: 'Wet Valley',
    temperature: 58,
    condition: WeatherCondition.rain,
    feelsLike: 55,
    high: 64,
    low: 54,
    humidity: 75,
    windSpeedMph: 8,
    uvIndex: 1,
    pressureInHg: 29.95,
    precipChance: 55,
    totalRainInches: 0.12,
    visibilityMiles: 7,
    windDirectionCompass: 'E',
    windBearingDegrees: 90,
    sunriseTime: '6:00 AM',
    sunsetTime: '8:00 PM',
    daylightDuration: '14h 0m',
    dailySummary: 'Light rain passing through.',
    riskLevel: 'LOW RISK',
    severeRisks: const <String, double>{},
    whatToExpect: const <String>['Rain', 'Damp'],
    impactScores: const <String, int>{'Weather': 1},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel heavyRain = WeatherModel(
    location: 'Downpour Ridge',
    temperature: 54,
    condition: WeatherCondition.rain,
    feelsLike: 51,
    high: 60,
    low: 52,
    humidity: 88,
    windSpeedMph: 12,
    uvIndex: 0,
    pressureInHg: 29.85,
    precipChance: 85,
    totalRainInches: 0.48,
    visibilityMiles: 4,
    windDirectionCompass: 'SE',
    windBearingDegrees: 135,
    sunriseTime: '5:55 AM',
    sunsetTime: '8:05 PM',
    daylightDuration: '14h 10m',
    dailySummary: 'Heavy rain throughout the day.',
    riskLevel: 'MODERATE RISK',
    severeRisks: const <String, double>{'Flooding': 0.3},
    whatToExpect: const <String>['Heavy rain', 'Wet'],
    impactScores: const <String, int>{'Weather': 3, 'Visibility': 2},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel thunderstorm = WeatherModel(
    location: 'Storm Center',
    temperature: 48,
    condition: WeatherCondition.storm,
    feelsLike: 44,
    high: 58,
    low: 48,
    humidity: 92,
    windSpeedMph: 28,
    uvIndex: 0,
    pressureInHg: 29.72,
    precipChance: 95,
    totalRainInches: 1.2,
    visibilityMiles: 2,
    windDirectionCompass: 'N',
    windBearingDegrees: 0,
    sunriseTime: '5:50 AM',
    sunsetTime: '8:10 PM',
    daylightDuration: '14h 20m',
    dailySummary: 'Severe thunderstorm with lightning.',
    riskLevel: 'HIGH RISK',
    severeRisks: const <String, double>{
      'Lightning': 0.8,
      'Hail': 0.5,
      'Flooding': 0.6,
    },
    whatToExpect: const <String>['Severe storm', 'Dangerous'],
    impactScores: const <String, int>{'Weather': 5, 'Visibility': 4},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel snow = WeatherModel(
    location: 'Snowy Pass',
    temperature: 28,
    condition: WeatherCondition.snow,
    feelsLike: 22,
    high: 32,
    low: 26,
    humidity: 85,
    windSpeedMph: 15,
    uvIndex: 2,
    pressureInHg: 29.98,
    precipChance: 80,
    totalRainInches: 0.48,
    visibilityMiles: 3,
    windDirectionCompass: 'NW',
    windBearingDegrees: 315,
    sunriseTime: '7:00 AM',
    sunsetTime: '5:30 PM',
    daylightDuration: '10h 30m',
    dailySummary: 'Active snowfall with wind gusts.',
    riskLevel: 'MODERATE RISK',
    severeRisks: const <String, double>{'Blizzard': 0.4},
    whatToExpect: const <String>['Snow', 'Windy'],
    impactScores: const <String, int>{'Weather': 3, 'Visibility': 3},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel fog = WeatherModel(
    location: 'Fog Valley',
    temperature: 48,
    condition: WeatherCondition.fog,
    feelsLike: 46,
    high: 54,
    low: 46,
    humidity: 95,
    windSpeedMph: 2,
    uvIndex: 1,
    pressureInHg: 30.05,
    precipChance: 30,
    totalRainInches: 0.04,
    visibilityMiles: 0.25,
    windDirectionCompass: 'Calm',
    windBearingDegrees: 0,
    sunriseTime: '6:20 AM',
    sunsetTime: '7:40 PM',
    daylightDuration: '13h 20m',
    dailySummary: 'Dense fog reduces visibility.',
    riskLevel: 'LOW RISK',
    severeRisks: const <String, double>{},
    whatToExpect: const <String>['Fog', 'Slow'],
    impactScores: const <String, int>{'Visibility': 3},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel windy = WeatherModel(
    location: 'Wind Ridge',
    temperature: 56,
    condition: WeatherCondition.sunny,
    feelsLike: 48,
    high: 62,
    low: 54,
    humidity: 42,
    windSpeedMph: 22,
    uvIndex: 6,
    pressureInHg: 30.00,
    precipChance: 5,
    totalRainInches: 0,
    visibilityMiles: 10,
    windDirectionCompass: 'W',
    windBearingDegrees: 270,
    sunriseTime: '6:10 AM',
    sunsetTime: '7:50 PM',
    daylightDuration: '13h 40m',
    dailySummary: 'Windy day with strong gusts.',
    riskLevel: 'LOW RISK',
    severeRisks: const <String, double>{},
    whatToExpect: const <String>['Windy', 'Breezy'],
    impactScores: const <String, int>{'Weather': 2},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel dawn = WeatherModel(
    location: 'Dawn City',
    temperature: 44,
    condition: WeatherCondition.sunny,
    feelsLike: 42,
    high: 72,
    low: 44,
    humidity: 52,
    windSpeedMph: 5,
    uvIndex: 1,
    pressureInHg: 30.10,
    precipChance: 0,
    totalRainInches: 0,
    visibilityMiles: 10,
    windDirectionCompass: 'SW',
    windBearingDegrees: 225,
    sunriseTime: '6:30 AM',
    sunsetTime: '7:30 PM',
    daylightDuration: '13h 0m',
    dailySummary: 'Dawn breaks over a clear horizon.',
    riskLevel: 'LOW RISK',
    severeRisks: const <String, double>{},
    whatToExpect: const <String>['Clear', 'Cool'],
    impactScores: const <String, int>{'Weather': 0},
    hourly: const <HourlyForecast>[],
  );

  static final WeatherModel dusk = WeatherModel(
    location: 'Dusk Valley',
    temperature: 62,
    condition: WeatherCondition.sunny,
    feelsLike: 61,
    high: 76,
    low: 58,
    humidity: 48,
    windSpeedMph: 6,
    uvIndex: 2,
    pressureInHg: 30.08,
    precipChance: 0,
    totalRainInches: 0,
    visibilityMiles: 10,
    windDirectionCompass: 'SW',
    windBearingDegrees: 225,
    sunriseTime: '6:00 AM',
    sunsetTime: '8:00 PM',
    daylightDuration: '14h 0m',
    dailySummary: 'Golden hour approaches with clear skies.',
    riskLevel: 'LOW RISK',
    severeRisks: const <String, double>{},
    whatToExpect: const <String>['Golden', 'Clear'],
    impactScores: const <String, int>{'Weather': 0},
    hourly: const <HourlyForecast>[],
  );
}
