import 'daily_forecast_item.dart';
import 'hourly_forecast.dart';
import 'weather_condition.dart';
import 'weather_model.dart';

abstract final class MockWeather {
  static const WeatherModel newYorkRain = WeatherModel(
    location: 'New York, NY',
    temperature: 71,
    condition: WeatherCondition.rain,
    feelsLike: 69,
    high: 72,
    low: 62,
    humidity: 93,
    windSpeedMph: 12,
    uvIndex: 1,
    pressureInHg: 29.92,
    precipChance: 90,
    totalRainInches: 0.80,
    visibilityMiles: 8.0,
    windDirectionCompass: 'ESE',
    windBearingDegrees: 112.0,
    sunriseTime: '5:36 AM',
    sunsetTime: '8:08 PM',
    daylightDuration: '14h 32m',
    dailySummary: 'Rainy with a high chance of showers and thunderstorms.',
    riskLevel: 'LOW RISK',
    severeRisks: <String, double>{
      'rain': 0.85,
      'thunderstorms': 0.55,
      'flooding': 0.50,
      'wind': 0.25,
      'hail': 0.20,
      'tornado': 0.05,
    },
    whatToExpect: <String>[
      'Bring an umbrella',
      'Slick roads possible',
      'Thunderstorms this afternoon',
      'Heavy rain around midday',
      'Plan for delays',
    ],
    impactScores: <String, int>{
      'Driving': 80,
      'Outdoor Plans': 30,
      'Construction': 35,
      'Running': 20,
      'Flying Drones': 15,
      'Photography': 25,
    },
    hourly: <HourlyForecast>[
      HourlyForecast(
        timeLabel: '6 AM',
        temperature: 64,
        condition: WeatherCondition.cloudy,
        precipChance: 20,
        threatLevel: 'low',
      ),
      HourlyForecast(
        timeLabel: '8 AM',
        temperature: 66,
        condition: WeatherCondition.rain,
        precipChance: 40,
        threatLevel: 'moderate',
      ),
      HourlyForecast(
        timeLabel: '10 AM',
        temperature: 68,
        condition: WeatherCondition.rain,
        precipChance: 70,
        threatLevel: 'moderate',
      ),
      HourlyForecast(
        timeLabel: '12 PM',
        temperature: 71,
        condition: WeatherCondition.rain,
        precipChance: 90,
        threatLevel: 'high',
        isNow: true,
      ),
      HourlyForecast(
        timeLabel: '2 PM',
        temperature: 72,
        condition: WeatherCondition.storm,
        precipChance: 90,
        threatLevel: 'high',
      ),
      HourlyForecast(
        timeLabel: '5 PM',
        temperature: 70,
        condition: WeatherCondition.rain,
        precipChance: 60,
        threatLevel: 'moderate',
      ),
      HourlyForecast(
        timeLabel: '8 PM',
        temperature: 66,
        condition: WeatherCondition.cloudy,
        precipChance: 30,
        threatLevel: 'moderate',
      ),
      HourlyForecast(
        timeLabel: '11 PM',
        temperature: 64,
        condition: WeatherCondition.cloudy,
        precipChance: 20,
        threatLevel: 'low',
      ),
    ],
    dailyForecasts: <DailyForecastItem>[
      DailyForecastItem(
        dayLabel: 'Today',
        condition: WeatherCondition.rain,
        high: 72,
        low: 62,
        precipChance: 90,
        uvIndex: 1,
        totalRainInches: 0.80,
      ),
      DailyForecastItem(
        dayLabel: 'Tomorrow',
        condition: WeatherCondition.storm,
        high: 74,
        low: 65,
        precipChance: 85,
        uvIndex: 4,
        totalRainInches: 1.10,
      ),
      DailyForecastItem(
        dayLabel: 'Thu',
        condition: WeatherCondition.rain,
        high: 70,
        low: 61,
        precipChance: 60,
        uvIndex: 5,
        totalRainInches: 0.35,
      ),
      DailyForecastItem(
        dayLabel: 'Fri',
        condition: WeatherCondition.cloudy,
        high: 76,
        low: 59,
        precipChance: 20,
        uvIndex: 6,
        totalRainInches: 0.0,
      ),
      DailyForecastItem(
        dayLabel: 'Sat',
        condition: WeatherCondition.sunny,
        high: 79,
        low: 62,
        precipChance: 5,
        uvIndex: 8,
        totalRainInches: 0.0,
      ),
      DailyForecastItem(
        dayLabel: 'Sun',
        condition: WeatherCondition.sunny,
        high: 81,
        low: 64,
        precipChance: 0,
        uvIndex: 8,
        totalRainInches: 0.0,
      ),
      DailyForecastItem(
        dayLabel: 'Mon',
        condition: WeatherCondition.cloudy,
        high: 77,
        low: 63,
        precipChance: 15,
        uvIndex: 6,
        totalRainInches: 0.0,
      ),
    ],
  );

  static final WeatherModel newYorkStorm = WeatherModel(
    location: 'New York, NY',
    temperature: 65,
    condition: WeatherCondition.storm,
    feelsLike: 59,
    high: 68,
    low: 57,
    humidity: 98,
    windSpeedMph: 28,
    uvIndex: 0,
    pressureInHg: 29.55,
    precipChance: 100,
    totalRainInches: 1.65,
    visibilityMiles: 3.0,
    windDirectionCompass: 'SSE',
    windBearingDegrees: 157,
    dailySummary:
        'Severe thunderstorms with frequent lightning and heavy rain.',
    riskLevel: 'HIGH RISK',
    severeRisks: const <String, double>{
      'rain': 0.95,
      'thunderstorms': 0.95,
      'flooding': 0.75,
      'wind': 0.70,
      'hail': 0.40,
      'tornado': 0.15,
    },
    whatToExpect: const <String>[
      'Avoid exposed outdoor areas',
      'Expect flooded roadways',
      'Seek shelter during lightning',
    ],
    impactScores: const <String, int>{
      'Driving': 30,
      'Outdoor Plans': 5,
      'Construction': 10,
      'Running': 5,
      'Flying Drones': 0,
      'Photography': 10,
    },
    hourly: const <HourlyForecast>[
      HourlyForecast(
        timeLabel: '6 AM',
        temperature: 61,
        condition: WeatherCondition.storm,
        precipChance: 85,
        threatLevel: 'high',
      ),
      HourlyForecast(
        timeLabel: '8 AM',
        temperature: 63,
        condition: WeatherCondition.storm,
        precipChance: 95,
        threatLevel: 'high',
      ),
      HourlyForecast(
        timeLabel: '10 AM',
        temperature: 65,
        condition: WeatherCondition.storm,
        precipChance: 100,
        threatLevel: 'high',
      ),
      HourlyForecast(
        timeLabel: '12 PM',
        temperature: 65,
        condition: WeatherCondition.storm,
        precipChance: 100,
        threatLevel: 'high',
        isNow: true,
      ),
      HourlyForecast(
        timeLabel: '2 PM',
        temperature: 66,
        condition: WeatherCondition.storm,
        precipChance: 100,
        threatLevel: 'high',
      ),
      HourlyForecast(
        timeLabel: '5 PM',
        temperature: 64,
        condition: WeatherCondition.storm,
        precipChance: 95,
        threatLevel: 'high',
      ),
      HourlyForecast(
        timeLabel: '8 PM',
        temperature: 61,
        condition: WeatherCondition.rain,
        precipChance: 80,
        threatLevel: 'high',
      ),
      HourlyForecast(
        timeLabel: '11 PM',
        temperature: 59,
        condition: WeatherCondition.cloudy,
        precipChance: 40,
        threatLevel: 'moderate',
      ),
    ],
    dailyForecasts: const <DailyForecastItem>[
      DailyForecastItem(
        dayLabel: 'Today',
        condition: WeatherCondition.storm,
        high: 68,
        low: 57,
        precipChance: 100,
        uvIndex: 0,
        totalRainInches: 1.65,
      ),
      DailyForecastItem(
        dayLabel: 'Tomorrow',
        condition: WeatherCondition.storm,
        high: 70,
        low: 59,
        precipChance: 90,
        uvIndex: 1,
        totalRainInches: 1.10,
      ),
      DailyForecastItem(
        dayLabel: 'Thu',
        condition: WeatherCondition.rain,
        high: 69,
        low: 58,
        precipChance: 75,
        uvIndex: 2,
        totalRainInches: 0.60,
      ),
      DailyForecastItem(
        dayLabel: 'Fri',
        condition: WeatherCondition.cloudy,
        high: 72,
        low: 60,
        precipChance: 30,
        uvIndex: 4,
        totalRainInches: 0.05,
      ),
      DailyForecastItem(
        dayLabel: 'Sat',
        condition: WeatherCondition.sunny,
        high: 77,
        low: 62,
        precipChance: 5,
        uvIndex: 7,
        totalRainInches: 0,
      ),
      DailyForecastItem(
        dayLabel: 'Sun',
        condition: WeatherCondition.sunny,
        high: 79,
        low: 63,
        precipChance: 0,
        uvIndex: 8,
        totalRainInches: 0,
      ),
      DailyForecastItem(
        dayLabel: 'Mon',
        condition: WeatherCondition.cloudy,
        high: 75,
        low: 61,
        precipChance: 20,
        uvIndex: 5,
        totalRainInches: 0,
      ),
    ],
  );
}
